blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/Jared-Godar/ecg_anomaly_detection/security/advisories/new
    about: Privately report a repository security vulnerability.
